### ISSUE TITLE
Menu item selection hard to see

### ISSUE THREAD

**Issue by pbomb** [chaseadamsio/vscode-theme-neon-night#23]
The contrast between the currently-selected menu item and the other menu items can be really hard to distinguish, especially on less-than-ideal monitors. Would it be possible to make the two background colors differ more than they currently do?

Thanks! I'm really liking this theme so far!

**Comment by predmijat** [comment]
Add this to your `settings.json`:
```
"workbench.colorCustomizations": {
        "list.focusBackground": "#DD92F633",
        "editorSuggestWidget.selectedBackground": "#DD92F633",
    },
```
Feel free to change the colors, these are from the palette.

**Comment by pbomb** [comment]
Awesome, thanks. That looks great. I'll submit a pull request to get this into the theme properly.
