### ISSUE TITLE
Cannot see the selected item

### ISSUE THREAD

**Issue by daveflr** [chaseadamsio/vscode-theme-neon-night#24]
no distinction between the selected menu and the rest of the items, when I try to autocomplete

![Video_2019-05-29_172915](https://user-images.githubusercontent.com/31354970/58598707-a9ccdc00-823a-11e9-96d9-764754318b65.gif)

**Comment by chaseadamsio** [comment]
Closed by #30 and released as a part of https://github.com/chaseadamsio/vscode-theme-neon-night/tree/v0.30.0 on 2019/12/01. Let me know if that helps!

**Comment by daveflr** [comment]
I see now, literally :smiley:
