### ISSUE TITLE
JSX highlighting

### ISSUE THREAD

**Issue by sfrench87** [chaseadamsio/vscode-theme-neon-night#27]
![code](https://user-images.githubusercontent.com/48254143/61115489-7c568d80-a48a-11e9-9c10-33c2124bd19c.png)

Tags aren't highlighted and attributes/embed braces aren't colored like the screenshots.

**Comment by chaseadamsio** [comment]
This is fixed in the latest release, sorry it took so long to resolve!

![image](https://user-images.githubusercontent.com/1024544/79678156-306d0d80-81ad-11ea-98bb-0969a031314a.png)
