### ISSUE TITLE
How do you do the dashed squiggle indicator?

### ISSUE THREAD

**Issue by JasonHoltzen** [chaseadamsio/vscode-theme-neon-night#45]
First, amazing theme, thank you.  The dashed squiggles are amazing and really help them to stand out.  I've been using it a couple of days and I'm getting a bit of eye strain off of the magenta, so I was looking at modifying another theme so I could still get the indicator.  I was wondering if you wouldn't mind sharing how you achieved that?

**Comment by curiouslychase** [comment]
Hey thanks!

Can you share a screenshot of the dashed squiggles you're referring to?

**Comment by JasonHoltzen** [comment]
![image](https://user-images.githubusercontent.com/4836968/108941971-b05cd300-761b-11eb-8aa6-3608faa7500b.png)

**Comment by curiouslychase** [comment]
Cool, those are the ones I was pretty sure you meant. You want to use these selectors:

`editorError.foreground`: error squiggles
`editorWarning.foreground`: warning squiggles
`editorInfo.foreground`: info squiggles

https://github.com/chaseadamsio/vscode-theme-neon-night/blob/mainline/src/colors/editor.js#L42-L45

you can set these on your workbench too (so you can use your favorite theme without forking) by adding them to your settings.json like this:


```

{
  "workbench.colorCustomizations": {
    "editorError.foreground": "#f00"
  }
}
```


You can read more about them [here](https://code.visualstudio.com/api/references/theme-color) and search for "Errors and warnings"

**Comment by JasonHoltzen** [comment]
You are amazing, thank you.
